### ISSUE TITLE
Custom properties don't get submitted to ElasticSearch after upgrading to 2.0.0 (from 1.1.0)

### ISSUE THREAD

**Issue by Dima234** [urielha/log4stash#10]
We have been successfully submitting custom properties using following log4net line, using log4stash 1.1.0

`LogicalThreadContext.Stacks["UserName"].Push("jsmith")`

This got broken with 1.1.1 (https://github.com/urielha/log4stash-old/issues/14). So we had to use older 1.1.0. I tried to upgrade to 2.0.0 today and instead of Count=1 log4stash does not seem to submit custom values at all.

Our appender configuration:

```
<appender name="ElasticSearchAppender" type="log4stash.ElasticSearchAppender, log4stash">
    <layout type="log4net.Layout.PatternLayout,log4net">
        <param name="ConversionPattern" value="%utcdate{ABSOLUTE} %-5level %logger - %message%newline" />
    </layout>
    <filter type="log4net.Filter.LevelRangeFilter">
        <levelMin value="WARN" />
        <levelMax value="FATAL" />
    </filter>
    <Server>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</Server>
    <Port>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</Port>
    <IndexName>log_%{+yyyy-MM-dd}</IndexName>
    <IndexType>LogEvent</IndexType>
    <Bulksize>2000</Bulksize>
    <BulkIdleTimeout>10000</BulkIdleTimeout>
    <IndexAsync>True</IndexAsync>
    <!-- Message|Exception|Properties -->
    <FixedFields>772</FixedFields>
    <SerializeObjects>false</SerializeObjects>
    <ElasticFilters>
    </ElasticFilters>
</appender>
```

**Comment by urielha** [comment]
Very weird, what you're saying is that the message is getting into Elastic but without any custom values?
Do you see any error message or any other indication?

Because I have added a specific test for custom values and I won't submit this version if the test wasn't pass... 

I hope I could test this soon with your config.
Please update if you have more insights.

Regards

**Comment by urielha** [comment]
I can't repro this on my local machine.
Do you still get the `count: 0` in you json or you get something else now?

Please check again that you are using the correct version and see if you can find any error message.

**Comment by jonhb** [comment]
I can't get custom properties to work either. I set them with GlobalContext.Properties["Guid"] and use %property{Guid} to access them. This works fine in fileappender but not in ElasticSearchAppender.

I get this in ES: "Guid": {}

Do I have to set something up in the config for these custom properties?
All I have is this:

```
    <appender name="ElasticSearchAppender" type="log4stash.ElasticSearchAppender, log4stash">
      <Server>localhost</Server>
      <Port>9200</Port>
      <IndexName>logstash-%{+yyyyMM}</IndexName>
      <IndexType>log</IndexType>
      <IndexAsync>true</IndexAsync>
    </appender>

```

**Comment by urielha** [comment]
Hi @jonhb and @Dima234 ,
Please try this pre release:
https://www.nuget.org/packages/log4stash/2.0.2-pre

Let me know if it fixed your issue.
Thanks

**Comment by jonhb** [comment]
Hi,

I still can't get it to work.

**Comment by urielha** [comment]
emmm... let's try another thing,
try to put:

``` xml
  <FixedFields>Partial</FixedFields>
```

inside your configuration file.
(so it will be:

``` xml
    <appender name="ElasticSearchAppender" type="log4stash.ElasticSearchAppender, log4stash">
        <Server>localhost</Server>
        <Port>9200</Port>
      <IndexName>logstash-%{+yyyyMM}</IndexName>
      <IndexType>log</IndexType>
      <IndexAsync>true</IndexAsync>

      <FixedFields>Partial</FixedFields>

    </appender>
```

And furthermore, I noticed that you said you 

> use %property{Guid} to access them

Where do you use it?

Hope the `FixedFields` will make it work.

Cheers

**Comment by jonhb** [comment]
Hi,

I use it where I define the output pattern for the RollingFileAppender (and also where i define parameters for the SQL server appender):

`<layout type="log4net.Layout.PatternLayout">
<param name="ConversionPattern" value="%d{yyyy-MM-dd HH:mm:ss} [%property{Guid}] %p %m %n " />
</layout>
`

This outputs the Guid correctly in the file. In the code I set the Guid through a provider class where I have overridden the ToString method to return the Guid variable.
This is only initialized once:
`log4net.GlobalContext.Properties["Guid"] = new GuidProvider();
`
and then this returns the dynamic Guid:
`public class GuidProvider { public override string ToString() { return Guid; } }`

The FixedFields does not help anything unfortunatly.

**Comment by urielha** [comment]
Thanks, I'm pretty sure I found the problem.

Will update you soon with new version.

Note that your problem is different from the author of this thread that is why I got a bit confused at first.

**Comment by urielha** [comment]
Forgot to ask, Is there a reason you don't call toString inline?
like this:

`log4net.GlobalContext.Properties["Guid"] = new GuidProvider().toString();`

**Comment by jonhb** [comment]
I don't think that will work.

**Comment by urielha** [comment]
### Please use this version

https://www.nuget.org/packages/log4stash/2.0.2-b

## 

### @jonhb, Add this to your configuration :

``` xml
<ElasticFilters>

  <Convert>
    <ToString>Guid</ToString>
  </Convert>

</ElasticFilters>
```

This will cause calling the `ToString()` function before indexing into ElasticSearch.

## 

### @Dima234, Add this to your configuration:

``` xml
<ElasticFilters>

 <Convert>
    <ToString>UserName</ToString>
    <ToArray>
      <SourceKey>UserName</SourceKey>
    </ToArray>
  </Convert>

</ElasticFilters>
```

This will cause calling `ToString()` of the stack object and then convert the values to array.

## 

If you both already have `ElasticFilters` just add the `Convert` into it.
And please open new issue if the problem still occurs.

All the best,
Uriel
