### ISSUE TITLE
Not possible to have more than one Convert filter?

### ISSUE THREAD

**Issue by jonhb** [urielha/log4stash#12]
Hi,

Regarding issue #10 I have now tested it and it works fine with only one custom property. I have more than one property that needs this conversion. When I add a new convert-filter I does not log anything to ES at all? 

```
      <ElasticFilters>
        <Convert>
          <ToString>Guid</ToString>
        </Convert>
        <Convert>
          <ToString>Property2</ToString>
        </Convert>
      </ElasticFilters> 

```

**Comment by urielha** [comment]
Hi, I am glad to hear :smile: 

The convert hasn't fully tested yet but my intention was to use **only one** Convert tag and put all the conversions inside it.

Try this:

``` xml
      <ElasticFilters>
        <Convert>
          <ToString>Guid</ToString>
          <ToString>Property2</ToString>
        </Convert>
      </ElasticFilters> 
```

**Comment by jonhb** [comment]
Already tried that, did not work. Seems it works if the second property is blank (null) but not when it has a value.

**Comment by urielha** [comment]
That's odd.
Can you add into your app.config (or web.config) the following configuration:

``` xml
    <system.diagnostics>
        <trace autoflush="true">
            <listeners>
                <add 
                    name="textWriterTraceListener" 
                    type="System.Diagnostics.TextWriterTraceListener" 
                    initializeData="C:\temp\log4net.txt" />
            </listeners>
        </trace>
    </system.diagnostics>
```

And tell me if you see any error messages regarding to the `Convert` ?

**Comment by jonhb** [comment]
Tried it, nothing in the log.

**Comment by jonhb** [comment]
Got this to work. Problem was that I of course had inconsistent data since I already had documents with {} in ES.

**Comment by urielha** [comment]
Glad to hear :smile:
