### ISSUE TITLE
ToInt converter

### ISSUE THREAD

**Issue by jonhb** [urielha/log4stash#13]
Hi,

With reference to #10 , I had to add a ToInt converter to get all my data correctly in ES. Is this something you could add in your official release so I don't have to use a custom build?

**Comment by urielha** [comment]
Yeah, You can also open a pull request :)

**Comment by urielha** [comment]
Try this prerelease:
https://www.nuget.org/packages/log4stash/2.0.2-c

**Comment by urielha** [comment]
Close from inactivity
