### ISSUE TITLE
Can't convert field type to Int

### ISSUE THREAD

**Issue by saintmodx** [urielha/log4stash#23]
Hi, I'm trying to convert some fields after parsing message through Grok pattern. Field still have "string"  type in ElasticSearch instead of integer. 

Here is my appender configuration:

``` xml
<appender name="ElasticSearchAppender" type="log4stash.ElasticSearchAppender, log4stash">
  <Server>localhost</Server>
  <Port>9200</Port>
  <IndexName>dev</IndexName>
  <ElasticFilters>
    <Filter type="log4stash.Filters.RenameKeyFilter, log4stash">
      <Key>processId</Key>
      <RenameTo>ServiceName</RenameTo>
    </Filter>
    <Grok>
      <SourceKey>Message</SourceKey>
      <Pattern>%{WORD:ResponseCode} %{WORD:Method} %{URIPATH:Url} %{WORD:ElapsedMls} %{GREEDYDATA:StatusMessage}</Pattern>
    </Grok>
    <Convert>
      <ToInt>ResponseCode</ToInt>
      <ToInt>ElapsedMls</ToInt>
    </Convert>
  </ElasticFilters>
  <filter type="log4stash.Filter.LevelRangeFilter">
    <levelMin value="INFO" />
    <levelMax value="ERROR" />
  </filter>
</appender>
```

I've also tried to use BASE10NUM and NUMBER instead of WORD. It doesn't work. Every time I change pattern I delete my current index in ElasticSearch before indexing it again to make sure it is fresh. So the question is how to convert field type from string to integer. 

Thanks,
Alex

**Comment by eran-gil** [comment]
I believe you need to set the mapping in your ElasticSearch cluster to define these fields' types to be integer, as ElasticSearch's default type for fields is string. You can do so by defining the mapping by yourself through the ElasticSearch API or plugins like 'Sense', or you can use the template configuration for the appender and define your fields as integer in the template's json file, which will put this mapping on the server.

**Comment by saintmodx** [comment]
Ok, it is clear. Thank you for the information.
