### ISSUE TITLE
NuGet package for 2.0.4

### ISSUE THREAD

**Issue by secovel** [urielha/log4stash#25]
Can you release a new NuGet package for 2.0.4?  Thanks!

**Comment by youliny** [comment]
the same issues.current nugget package version is 2.0.1.

**Comment by urielha** [comment]
Hope it will be ready soon :) 
Sorry it taking me time, I invest in this project in my free time and I don't have much time these days =/

**Comment by urielha** [comment]
@secovel , @youliny , @erangil2 
Have fun with [log4stash 2.0.4](https://www.nuget.org/packages/log4stash/2.0.4) and keep me updated if you found issues! :)
