### ISSUE TITLE
Make compatible with .NET Core

### ISSUE THREAD

**Issue by steelheaddigital** [urielha/log4stash#26]

**Comment by wparsons-360insights** [comment]
I'd love .netcore support as well, and would be willing to help contribute and/or test.

**Comment by steelheaddigital** [comment]
@wparsons-360insights, I've started using [serilog ](https://serilog.net/)in my .NET core projects. It works well with .NET core and has a working .NET Core [sink ](https://github.com/serilog/serilog-sinks-elasticsearch)to write to Elasticsearch. If you need something right away, that is a good way to go.

**Comment by wparsons-360insights** [comment]
We already have logstash setup, so I could just write to log files and ship them through logstash in the short term.  I just prefer skipping a file step if not needed.

I'll take a look at serilog though, might be a good interim solution.

**Comment by urielha** [comment]
@wparsons-360insights It would be awesome if you can contribute :)
Currently I don't have any strict methods of pull request, so just make your change and open a pull request.

I hope I will have time to do it myself but this is not the situation right now... sorry.

**Comment by urielha** [comment]
Don't think I will do this. You are welcome to open a pull request and I will gladly approve it.

**Comment by urielha** [comment]
Thanks to @erangil2 this should be working soon!
