### ISSUE TITLE
Basic Authentication problem

### ISSUE THREAD

**Issue by bahim** [urielha/log4stash#27]
hi,

I'm using log4stash(2.01 and log4net 2.05) to write logs to elasticsearch with x-pack security enabled. I tried to use basic authentication method in my appender (same appender  in your README) but i have a 401 error and this message in my application logs: 

> log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [AuthenticationMethod] to set object on [log4stash.ElasticSearchAppender]

**Comment by urielha** [comment]
Hi,
**Update:** Please download [log4stash 2.0.4](https://www.nuget.org/packages/log4stash/2.0.4) It should work for you :)

------
**old comment:**
This feature is part of the next version (I'm currently working on releasing it).
To use the basic authentication of 2.0.1 version you need to use this:

```xml
<appender name="ElasticSearchAppender" type="log4stash.ElasticSearchAppender, log4stash">
    <Server>server</Server>
    <Port>port</Port>
    <!-- other configurations -->
    <BasicAuthUsername>Username</BasicAuthUsername>
    <BasicAuthPassword>Password</BasicAuthPassword>
</appender>
```

I'm sorry for the inconvenience 
Let me know if this worked for you.

**Comment by bahim** [comment]
Hi,

It worked, thank you !
