### ISSUE TITLE
Integration with .NET Projects

### ISSUE THREAD

**Issue by nickofranco** [urielha/log4stash#29]
Hi,

Just wanna ask regarding the integration with .NET projects, is it the same on how log4net.ElasticSearch is implemented? 

Thank you :)

**Comment by urielha** [comment]
What do you mean  by that?
The configuration is completely different from log4net.ElasticSearch
But this is still a nuget package and you can install it the same way as you install log4net.ElasticSearch.

Hope I answered your question, if not, please be more specific.

**Comment by nickofranco** [comment]
Hi,

Thanks for the response. I've successfully got it running on our project. Many thanks for this project :)

**Comment by urielha** [comment]
Glad to hear :)
