### ISSUE TITLE
Error logging to Elastic Cloud

### ISSUE THREAD

**Issue by Cylindric** [urielha/log4stash#35]
Hi. I am trying to log to our Elastic Cloud instance using 2.0.4, and I get an error:

```
log4net:ERROR Got error while reading response from ElasticSearch
System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at log4stash.WebElasticClient.<>c__DisplayClass4.<FinishGetResponse>b__3() in c:\Uriel\log4stash\src\log4stash\ElasticClient\ElasticClient.cs:line 127
   at log4stash.WebElasticClient.SafeGetAndCheckResponse(Func`1 getResponse) in c:\Uriel\log4stash\src\log4stash\ElasticClient\ElasticClient.cs:line 198
2
```

The appender config I have is fairly simple, and I have verified the credentials:

    <appender name="ElasticSearchAppender" type="log4stash.ElasticSearchAppender, log4stash">
      <Server>myinstanceid.eu-west-1.aws.found.io</Server>
      <Port>9243</Port>
      <IndexName>remoteadmin-%{+yyyy.MM.dd}</IndexName>
      <AuthenticationMethod>
        <Basic>
          <Username>myusername</Username>
          <Password>mypassword</Password>
        </Basic>
      </AuthenticationMethod>
    </appender>

Do you have an suggestions on how I might diagnose this?

Thanks.

**Comment by urielha** [comment]
It seems like a server problem, did you check the elastic logs?
Can you debug your app? Another suggestion is that you can load log4stash code and examine the exception while it occurs​..

**Comment by Cylindric** [comment]
This is Elastic Cloud, so I can't see any server logs, and the app debugging doesn't show anything more than that generic error. I'd be surprised if it's on the server side, as the other apps we have that use NLog seem to be working fine.

**Comment by urielha** [comment]
What is the Elastic version that you use?

**Comment by Cylindric** [comment]
The cloud platform is currently on 5.4.0

**Comment by HarveyEV** [comment]
Any update on this issue? Also, elastic cloud uses an SSL endpoint **(https://myinstanceid.eu-west-1.aws.found.io:<port>)**. How is that configured?

**Comment by urielha** [comment]
Hi @HarveyEV , @Cylindric 

I tried to log into elastic cloud by myself and found it roughly working.
There are errors in the check response function but the data is getting saved into the Elastic server.

Make sure you are using these configuration properties as described:

```xml
    <appender name="ElasticSearchAppender" type="log4stash.ElasticSearchAppender, log4stash">
        <Ssl>True</Ssl>
        <Servers>
            <Server>
                <Address>yourClientId.server.aws.found.io</Address>
                <Port>port_number</Port>
            </Server>
        </Servers>
        <AuthenticationMethod>
            <Basic>
                <Username>Username</Username>
                <Password>Password</Password>
            </Basic>
        </AuthenticationMethod>

        <!-- Other configurations -->
        <!-- ...... -->
    </appender>
```
I will investigate the response errors and hope to release an update soon.
Please update if you succeeded with the new configuration.

Uriel

**Comment by urielha** [comment]
Good news! 
Only the put template operation is throwing an error.
Until I will update the template operation I recommend you to put it by yourself and comment out it's part from the configuration.

Edit:
If this still throwing errors, please add this into the configuration:

```xml
    <IndexAsync>True</IndexAsync>
```

**Comment by urielha** [comment]
Hi, 
please try log4stash's new version: https://www.nuget.org/packages/log4stash/2.1.0

#### Note: 
I upgraded the log4net version to 2.0.8. 
If you still want to use the old 2.0.5 log4net just install this version of log4stash instead of the version above:
https://www.nuget.org/packages/log4stash/2.1.0-vip205
