### ISSUE TITLE
allow preserve array on flattenjson

### ISSUE THREAD

**Issue by osckal** [urielha/log4stash#38]
can add an option (or maybe keynames) to preserve array when flattenjson is true.. i prefer the format the "flattenjson" option gives on the document for my object, except on array elements.

**Comment by urielha** [comment]
Thanks for the idea! unfortunately I'm very busy lately so it will take me a little time. 
Hope to update soon.

**Comment by osckal** [comment]
@urielha 
I downloaded the source and made some changes on on the JsonFilter.cs.. and it seems to work
``` 
 case JTokenType.Array:
	var index = 0;
	bool arrObj = false;
	if (PreservePrimitiveArray)
	{
		foreach (var child in token.Children<JObject>())
		{
			// check if its an array of objects
			if (child.Type == JTokenType.Object)
			{
				ScanToken(logEvent, child.Value<JToken>(), Join(prefix, index.ToString()));
				index++;
				arrObj = true;
				break;
			}
		}
		if (!arrObj)
		{
			logEvent.Add(prefix, token);
		}
	}
	else
	{
		foreach (var child in token.Children())
		{
			ScanToken(logEvent, child, Join(prefix, index.ToString()));
			index++;
		}
	}


	break;
```

**Comment by urielha** [comment]
Hi @osckal ,
I will see what I can do.

Meanwhile, one of the things that great in that filters is that you can **write one of your own and make log4stash load it for you.**
I suggest you to compile the changes you have made to the filter and add it to your configuration.
You can just compile this file (with a reference to log4stash.dll for importing the filter interface) and load it by configuration like that:

```xml
     <Filter type="log4stash.Filters.NameOfTheFilter, filename">
          <!-- rest of configuration -->
      </Filter>
```

**Comment by osckal** [comment]
Hi @urielha ,

Thanks for the advise! I think i'll try that one out and see how it goes. anyway, it looks like I had more changes than expected. 

Thanks!

**Comment by urielha** [comment]
You are welcome :)
Feel free to reopen this issue or open new one if you have trouble with loading your custom filter
