### ISSUE TITLE
Error 406 with ElasticSearch 6.0 RC 2

### ISSUE THREAD

**Issue by beckma** [urielha/log4stash#40]
In **ElasticSearch 6.0 RC 2** this error occurs:

![image](https://user-images.githubusercontent.com/6991499/32319659-9f4cc472-bfbb-11e7-9ab2-b78660f19fa1.png)

![image](https://user-images.githubusercontent.com/6991499/32319693-b9d527bc-bfbb-11e7-828c-4bb9bf083146.png)

Maybe it's a similar problem like this (log4net.ElasticSearch):

https://github.com/jptoto/log4net.ElasticSearch/issues/86

Thanks.

Best regards
Martin

**Comment by urielha** [comment]
Thanks! I already pushed a change which maybe fix that :)
I will publish new release soon and update this issue.

**Comment by urielha** [comment]
Try the new version: https://www.nuget.org/packages/log4stash/2.1.0
:)

#### Note: 
I upgraded the log4net version to 2.0.8. 
If you still want to use the old 2.0.5 log4net just install this version of log4stash instead of the version above:
https://www.nuget.org/packages/log4stash/2.1.0-vip205

**Comment by urielha** [comment]
Please reopen if still occurred
