### ISSUE TITLE
Custom Eventlog Data

### ISSUE THREAD

**Issue by adibenmat** [urielha/log4stash#43]
Is there a way to make the add or remove properties from the logEvent,
I would want remove unnecessary properies like AppDomain, and move all the properies of "MessageObject", outside of the warpping
 {
                "_index": "slog_20171218",
                "_type": "LogEvent",
                "_id": "v_cNaWABDFhcUDArB-sp",
                "_score": 1,
                "_source": {
                    "@timestamp": "2017-12-18T09:55:49.0362522Z",
                    "LoggerName": "Log4NETTest.Program",
                    "HostName": "ADIPTOP",
                    "ThreadName": "1",
                    "AppDomain": "Log4NETTest.exe",
                    "Level": "INFO",
                    "Message": "Log4NETTest.LogObject",
                    "MessageObject": {
                        "RawReading": null,
                        "Severity": null,
                        "Message": null,
                        "CorrelationId": null,
                        "TimeStamp": "0001-01-01T00:00:00",
                        "BoltName": null,
                        "InternalTimestamp": "0001-01-01T00:00:00",
                        "ReadingTimestamp": "0001-01-01T00:00:00",
                        "AppId": null,
                        "DeviceId": null,
                        "ProductId": null,
                        "Unit": null,
                        "TypeCode": 0,
                        "Name": "something new",
                        "Value": null
                    },
                    "log4net:Identity": "",
                    "log4net:UserName": "ADIPTOP\\Adi",
                    "log4net:HostName": "Adiptop"
                }
            },

**Comment by urielha** [comment]
There are two ways you can remove fields:
 * Using `FixedFields` configuration parameter
 * Using `Remove` Filter


#### Using `FixedFields` configuration parameter:
If all you want is to remove all the default fields from log4net you might use the `FixedFields` configuration, For example to remove all but the message use this:

```xml
<FixedFields>Message</FixedFields>
```

You can also combine two or more fields.
To read more about FixedFields please refer to [log4net.Core.FixFlags][log4net-fixed-fields]

#### Using `Remove` Filter:

For example to remove the `ThreadName` just add this to your configuration:

```xml
<ElasticFilters>
    <Remove>
        <Key>ThreadName</Key>
    </Remove>
</ElasticFilters>
```

Take a look at these filters for more information:

* [**Add**][docs-filters-add] - add new key and value to the event.
* [**Remove**][docs-filters-remove] - remove key from the event.
* [**Rename**][docs-filters-rename] - rename key to another name.


Unfortunately there is no way to **move** field from inner place to outer, if more folks will desire such behavior I will try to add it.


[docs-filters-add]:https://github.com/urielha/log4stash/blob/master/docs/Filters/Add.md
[docs-filters-remove]:https://github.com/urielha/log4stash/blob/master/docs/Filters/Remove.md
[docs-filters-rename]:https://github.com/urielha/log4stash/blob/master/docs/Filters/Rename.md
[log4net-fixed-fields]:https://logging.apache.org/log4net/release/sdk/html/T_log4net_Core_FixFlags.htm

**Comment by adibenmat** [comment]
That sums it up,
Thanks!!!
