### ISSUE TITLE
Custom authenitcation method

### ISSUE THREAD

**Issue by mrkothari** [urielha/log4stash#44]
Is it possible to hook-in custom authentication method ? In our ELK setup for authentication we have to set some custom header, so would need to write a custom authentication handler.

**Comment by urielha** [comment]
Emm actually there is, thanks to @erangil2 :)
But I haven't try this so let's hope it will work.

You need to create your own AuthenticationMethod class which will implement from `log4stash.Authentication.IAuthenticationMethod`

Now in your configuration you need to add this:

```xml
   <AuthenticationMethod>
      <Filter type="yourNameSpace.Inner.MyAuthenticationMethod, nameOfTheDll">
          <CustomParameter>Parameter</CustomParameter>
          <!-- more custom parameters -->
      </Filter>
    </AuthenticationMethod>
```

### Pay attention to:
 * `yourNameSpace.Inner.MyAuthenticationMethod` should be the full namespace + name of your custom authentication class.


 * `nameOfTheDll` should be the name of the dll which contains the class (should be at the same folder with your app).

* `<CustomParameter>`  can be any public property with setter which your class has.

* The tag name `Filter` is not a mistake, I should have give it a more suitable name, maybe at the future.

Give it a try and let me know if you succeeded.
