### ISSUE TITLE
netstandard issue

### ISSUE THREAD

**Issue by mynkow** [urielha/log4stash#54]
I was looking into this library and in the readme it says that .netcore is supported. However the nuget package has moniker for netstandard2.0 but not a folder with actual dlls for it => https://gyazo.com/fac6bcb1bb76e1f689c640e0631b2f7e

When installed in a project which targets netstandard2.0 VS prompts for an error which is expected => https://gyazo.com/73ac8351d7f31b3ee319ac5b5bd49a12

1) Did you use this library in netstandard/.netcore project?
2) Could you please build a proper nuget package or point us how to install it?

**Comment by eran-gil** [comment]
Hey,
I've tested this library with .net standard and asp.net core and it works very well.
The screenshot you attached shows a **warning** and not an **error**.
This should work as it is.
@urielha I think in future versions we should improve that.

**Comment by aregaz** [comment]
@erangil2 well, it would work on Windows for sure, but have you tested it on Linux or in Docker? I have the same warnings and I believe it would not work in Docker.

**Comment by eran-gil** [comment]
I actually did test it. I have multiple production services running on OpenShift containers, which is a Linux container, and they are working perfectly with the appended, you should try it yourself 😉

**Comment by aregaz** [comment]
I just tested it in Docker on Ubuntu 16.04 - it is working. Hmm... I wonder why compiler show that warning then?

**Comment by eran-gil** [comment]
@aregaz It shows that so in case you have an error of any kind during runtime because of this issue you'll know where to look for it first.
However, it doesn't mean that by default it causes an error.

**Comment by mynkow** [comment]
Actually, the warning is shown because versions before 4.7.2 does not fully implement the netstadard2.0 interface. In 98% of the time you are OK.

**Comment by urielha** [comment]
Thanks for the update! 
We still need to fix that. I am not familiar enough with dotnet core so I will have to investigate a little bit this issue.

**Comment by hpfan** [comment]
add my test here: currently use log4stash 2.2.1 and target as netcore2.1 will throw warning "Package 'log4stash 2.2.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project." during build, and test it works well which record logs.

**Comment by uciprian** [comment]
In the package there is no distribution for netstandard

**Comment by mynkow** [comment]
@urielha way back we did a hardfork. If it helps you could get anything from there: https://github.com/Elders/log4net.Appender.ElasticSearch

**Comment by urielha** [comment]
Hi, now it should have :) 
Please check [version 3.0.0](https://www.nuget.org/packages/log4stash/)
And thanks to @erangil2 😄
