### ISSUE TITLE
Stopped working after upgrading Elastic to 2.2

### ISSUE THREAD

**Issue by urielha** [urielha/log4stash#6]
_From @MonDeveloper on March 11, 2016 0:36_

_Copied from original issue: urielha/log4stash-old#16_

**Comment by urielha** [comment]
Do you have any error message?

**Comment by eran-gil** [comment]
I succeeded in using it with elastic 2.3.
The error I had when logging was related to using the '_ttl' field with this configuration:

```
<ElasticFilters>
      <Add>
        <Key>_ttl</Key>
        <Value>3d</Value>
      </Add>
</ElasticFilters>
```

Any way of fixing it?

**Comment by urielha** [comment]
Hi, 
I have seen that _ttl parameter is deprecated in Elastic 2.*
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ttl-field.html

I haven't checked this myself already but maybe this is the issue.
Please update about your insights

**Comment by eran-gil** [comment]
Yep, I saw it has been deprecated after 2.0, but since they didn't provide any alternative they said it would work until they provide another way to do this. A friend said I might need to create a custom mapping  to make it work, but I remember that it used to work without any custom mapping.

**Comment by urielha** [comment]
For the mapping you can use the `<template>` option of log4stash.
Here is a gist [example of template](https://gist.github.com/urielha/fd6dbf29e40da96a7c768e0d8359d365) with ttl enabled.
Pay attention to configure the timestamp as date.

Have a look at the [config example](https://github.com/urielha/log4stash/blob/master/src/log4stash.Tests/logConfig.xml#L19,L22) from log4stash tests to see how to configure it.

If there are still problems I will try to test it myself later this week.
Best regards.

**Comment by urielha** [comment]
@MonDeveloper, Please open this again if you still have the issue after upgrading to 2.0.1
