### ISSUE TITLE
ApiKey Authentication

### ISSUE THREAD

**Issue by dannyyy** [urielha/log4stash#60]
Hi,

I have to move my applications from an 2.x Elasticsearch to a new 7.6 Elasticsearch.
The new server only allows ApiKey based authentication.

I've seen the issue #44 where you explain how to implement my own authenticator. I'm using the latest Version of log4stash and cannot find any interface like `log4stash.Authentication.IAuthenticationMethod`. The two existing authentication classes direves directly from `IAuthenticator`, an implemention of ReshSharp.

I followed the pattern as in #44 but I have no idea whether my filter is found by log4stash nor whether it's treated as valid, ... The only exception I get is `401 (Forbidden)`. But this error occures anyway.

This is my configuration:
```
    <log4net>
        <appender name="ElasticSearchAppender" type="log4stash.ElasticSearchAppender, log4stash" >
            <Server>hostname</Server>
            <Port>443</Port>
            <Ssl>true</Ssl>
            <AuthenticationMethod>
                <Filter type="company.departement.Package.Framework.Log.Log4StashApiKeyAuthenticator, company.departement.Package.Framework.Log">
                    <ApiKey>abc123</ApiKey>
                </Filter>
            </AuthenticationMethod>
            <IndexName>application-logstash-%{+yyyy.MM.dd}</IndexName>
            <IndexType>LogEvent</IndexType>
            <Bulksize>100</Bulksize>
            <BulkIdleTimeout>15</BulkIdleTimeout>
            <IndexAsync>True</IndexAsync>
            <ElasticFilters>
            </ElasticFilters>
            <layout type="log4net.Layout.PatternLayout">
                <conversionPattern value="%date [%thread] %-5level %logger [%property{NDC}] - %message%newline" />
            </layout>
        </appender>
        <root>
            <appender-ref ref="ElasticSearchAppender" />
        </root>
    </log4net>
```

And this is my authenticator implementation:
```
using RestSharp;
using RestSharp.Authenticators;

namespace company.departement.Package.Framework.Log
{
    public class Log4StashApiKeyAuthenticator : IAuthenticator
    {
        public string ApiKey { get; set; }
        
        public void Authenticate(IRestClient client, IRestRequest request)
        {
            request.AddHeader("Authorization", $"ApiKey {ApiKey}");
        }
    }
}
```
Is this scenario still support? If now, how to proceed with my api key?

Thank you and kind regards,
Danny

**Comment by eran-gil** [comment]
Try making a pull request with a new authenticator integrated into the library and we'll add it right into the library :)

**Comment by dannyyy** [comment]
@erangil2 Sounds great ;) At the moment I'm not confident how the mapping from the config to the respective authenticator works.

How does Log4Stash know, that e.g. `<Basic />` should map to the `BasicAuthenticationMethod`?

**Comment by eran-gil** [comment]
Look at  https://github.com/urielha/log4stash/blob/master/src/log4stash/Authentication/AuthenticationMethodChooser.cs
For each method we have a different "Add" method.
There should be a new "AddApiKey" method and then you could do it.
And as per your first post, we indeed changed the implementation to depend on IAuthenticator from RestSharp due to a refactor we did about a year ago.

**Comment by eran-gil** [comment]
make sure you put your api key correctly according to the instructions here: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/security-api-create-api-key.html

> The API key returned by this API can then be used by sending a request with a Authorization header with a value having the prefix ApiKey ` followed
> by the _credentials_, where _credentials_ is the base64 encoding of `id and api_key joined by a colon.

**Comment by dannyyy** [comment]
@erangil2  If you accept the pull request, do you mind to create a new NuGet package, so I can use it in my projects right away?

**Comment by eran-gil** [comment]
https://www.nuget.org/packages/log4stash/2.3.0
try this version and let us know if it works :)

**Comment by dannyyy** [comment]
@erangil2 @urielha 
Thank you! Version 2.3.0 works ;) I've seen that the file version of the assembly is still 2.2.0. But this doesn't affect the functionality or NuGet dependency resulution. Therefore, I close this issue.
