### ISSUE TITLE
Does not work with log4net 2.0.8 or higher

### ISSUE THREAD

**Issue by DmitryMak** [urielha/log4stash#69]
log4stash version is 3.0.0. Logging stopped working after upgrading log4net from 2.0.8 to 2.0.9. The only thing that changed is the version of log4net, everything else stayed the same. I enabled log4net debug output and I think it fails to load the appended because it is targeting 2.0.8 (as opposed to targeting 2.0.8 or higher):

```
log4net:ERROR Could not create Appender [ElasticSearchAppender] of type [log4stash.ElasticSearchAppender, log4stash]. Reported error follows.
System.IO.FileLoadException: Could not load file or assembly 'log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at log4net.Util.SystemInfo.GetTypeFromString(Assembly relativeAssembly, String typeName, Boolean throwOnError, Boolean ignoreCase)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

log4net:ERROR Appender named [ElasticSearchAppender] not found.
```

**Comment by eran-gil** [comment]
Hey, what version of the .Net Framework do you use?
Have you tried adding an assembly redirect to your app.config?
Try reading about it here: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by DmitryMak** [comment]
The project targets .NET Framework 4.8. Binding redirect helped. Please note that it has to be 2.0.9.0 even for log4net version 2.0.10. I think they forgot to update their assembly version.

```
<dependentAssembly>
	<assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
	<bindingRedirect oldVersion="0.0.0.0-2.0.9.0" newVersion="2.0.9.0" />
</dependentAssembly>
```

However I think that there might still be an issue with the way log4net dependency is specified by log4stash. Because msbuild usually prompts to add missing redirects. Is there a way for log4stash to work with 2.0.8 or above without redirect or make msbuild ask to add redirect?

**Comment by eran-gil** [comment]
Please look at that, it has to be in the project, not in the library:
https://blog.yaakov.online/automatically-generating-assembly-binding-redirects/

**Comment by DmitryMak** [comment]
> 
> 
> Please look at that, it has to be in the project, not in the library:
> https://blog.yaakov.online/automatically-generating-assembly-binding-redirects/

I understand that the redirect has to be in the config of the project. I was asking that log4stash should specify log4net dependency in such a way that if its missing, msbuild will issue a warning. This is still an issue for projects that can not have 'AutoGenerateBindingRedirects' option.

**Comment by DmitryMak** [comment]
FWIW, the binding redirect is still required as of latest versions of log4stash and log4net:

```
<dependentAssembly>
    <assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-2.0.12.0" newVersion="2.0.12.0" />
</dependentAssembly>
```
