### ISSUE TITLE
Target Elasticsearch index is incorrect

### ISSUE THREAD

**Issue by jdivy** [urielha/log4stash#83]
https://github.com/urielha/log4stash/blob/2212b1c0d338695f52e21be0ccea173199dfa857/src/log4stash/SmartFormatters/LogEventSmartFormatter.cs#L33

I'm encountering an odd behavior in our Grafana dashboard that I believe can be traced to this line of code.  I've seen references elsewhere on the internet to the fact that logs sent to elasticsearch are all expected to be UTC based and Grafana also makes the assumption that the dynamic rolling index name is _also_ UTC based.  The end result is Grafana expecting data to be in an index where it is not.  I'm in Central US time, so at this very moment there is data in the [indexname].2021.06.24 index but Grafana expects it would be in the [indexname].2021.06.25 index because we have just crossed the UTC threshold to the next day.  Grafana won't graph anything with a short time range until 4 hours from now, if that makes sense.  The log data itself seems correct.

I believe the simple fix is to use DateTime.UtcNow here instead of DateTime.Now when determining the index name to use.

**Comment by eran-gil** [comment]
You are welcome to look at #84, it should solve your issue.
The current mechanism can't be changed since it would be a breaking-change.
However, I added an option to use a different leading character in the format to use UTC zone instead of local.
Please let me know what you think

**Comment by jdivy** [comment]
Seems like the easiest non-breaking change and that would work for us!

**Comment by jdivy** [comment]
Thanks for releasing in https://github.com/urielha/log4stash/releases/tag/log4stash-3.0.4 !
