### ISSUE TITLE
application crash when elasticsearch server cannot be contacted

### ISSUE THREAD

**Issue by uciprian** [urielha/log4stash#9]
Hello, 

I'm using log4stash appender 2.0 and my application is failing when the elasticsearch server requests are timing out. 

But, I have a small patch for this how can I submit it?

**Comment by urielha** [comment]
Just sumbit new pull request from your repo.
(Try not submit any nuspec changes if any)
And I will check it.

Thanks for the contribution!!

**Comment by uciprian** [comment]
I've cloned your repo and added my fix, is it available at
https://github.com/uciprian/log4stash
I cannot find any option to create a pull request cross repos

Maybe you can help,
Thanks

Ciprian

**Comment by urielha** [comment]
Thanks, I don't have much time those days, I will take a look at this as soon as possible

**Comment by urielha** [comment]
Merged by pull request #11 
Thanks
